frontEnd:
    container:
        name: front-end
    image:
        pullPolicy: Always
        repository: robjahn/keptn-orders-front-end
        tag: 1
    replicaCount: 1
    resources:
        limits:
            cpu: 100m
            memory: 128Mi
        requests:
            cpu: 100m
            memory: 128Mi
    service:
        externalPort: 80
        internalPort: 8080
        name: front-end
customerService:
    container:
        name: customer-service
    image:
        pullPolicy: Always
        repository: robjahn/keptn-orders-customer-service
        tag: 1
    replicaCount: 1
    resources:
        limits:
            cpu: 100m
            memory: 128Mi
        requests:
            cpu: 100m
            memory: 128Mi
    service:
        externalPort: 80
        internalPort: 8080
        name: customer-service
orderService:
    container:
        name: order-service
    image:
        pullPolicy: Always
        repository: robjahn/keptn-orders-order-service
        tag: 1
    replicaCount: 1
    resources:
        limits:
            cpu: 100m
            memory: 128Mi
        requests:
            cpu: 100m
            memory: 128Mi
    service:
        externalPort: 80
        internalPort: 8080
        name: order-service
catalogService:
    container:
        name: catalog-service
    image:
        pullPolicy: Always
        repository: robjahn/keptn-orders-catalog-service
        tag: 1
    replicaCount: 1
    resources:
        limits:
            cpu: 100m
            memory: 128Mi
        requests:
            cpu: 100m
            memory: 128Mi
    service:
        externalPort: 80
        internalPort: 8080
        name: catalog-service
